### ISSUE TITLE
decodeByteArray fails on zero length strings

### ISSUE THREAD

**Issue by ccrossley** [loteixeira/as3-msgpack#1]
decodeByteArray() will read the remaining bytes of a message if it encounters a zero length string, bytearray or xml.

I got around this by adding if(length) before the read on line 257ish in TypeHandler.as.

**Comment by loteixeira** [comment]
Hello, ccrossley. Thanks for letting me know about the bug.
The project was already updated, and your contribution was added in the header of the file TypeHandler.as.
See you
