### ISSUE TITLE
I thought that String should be the default type for decoding raw bytes instead of ByteArray

### ISSUE THREAD

**Issue by sparkle** [loteixeira/as3-msgpack#2]
Because it's much common-usage, or can you make a switch for it. Thanks a lot.

**Comment by loteixeira** [comment]
Currently you'll always get a bytearray after decoding a string. And I guess there's no easy way to switch it.
I'm planing a new version soon, thus i'll check whether it's possible and/or important your request.
Thanks!

**Comment by loteixeira** [comment]
Hey. You were right.
Today i closed the new version of the api, and by default raw bytes are parsed as strings.
Also, your name is written at the code where the changes were done (RawWorker.as).
Thanks!
